### ISSUE TITLE
Better parent array for Floyd-Warshall

### ISSUE THREAD

**Issue by cassinius** [cassinius/GraphiniusJS#38]
Right now the FW implementation does not check if k is directly connected to j when updating the parent (next) array -> 

- introduce such a conditional check

- adapt all test cases and / or introduce new ones as necessary

- if possible, we should also change terminology from 'next' to 'parent' array

**Comment by ritavanellus** [comment]
Hi, 
in the meanwhile I have started exactly that :DThe conditional check (if there is direct connection between two nodes) is written and tested, it is working fine already.I am working on its implementation because for the first try it did not help... Maybe it is not so simple, because if there is a direct edge, it does not necessarily mean that that one is the shortest...? But now I go to sleep and continue tomorrow. 
Best, 
Rita





    On Wednesday, January 17, 2018, 9:53:48 PM GMT+1, Bernd Malle <notifications@github.com> wrote:  
 
 
Right now the FW implementation does not check if k is directly connected to j when updating the parent (next) array ->
   
   -    
introduce such a conditional check

   -    
adapt all test cases and / or introduce new ones as necessary

   -    
if possible, we should also change terminology from 'next' to 'parent' array

**Comment by ritavanellus** [comment]
Solved!!! 
Pls see code pushed on 28.01.2018
